version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi-app-api
    ports:
      - 8000:8000
    tty: true
    env_file:
      - ./env/.env
    depends_on:
      - postgres
    volumes:
      - ./app:/app
      - ./env:/env
    working_dir: /app

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    container_name: fastapi-app-db
    env_file:
      - ./env/.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - ./db/db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
